export const clothingTypes = {
  en: [
    "Sweater",
    "Dress",
    "Hoodies",
    "T-shirt",
    "Flip-flops",
    "Shorts",
    "Skirt",
    "Jeans",
    "Shoes",
    "Coat",
    "High heels",
    "Suit",
    "Cap",
    "Socks",
    "Shirt",
    "Bra",
    "Scarf",
    "Swimsuit",
    "Hat",
    "Gloves",
    "Jacket",
    "Long coat",
    "Boots",
    "Sunglasses",
    "Tie",
    "Polo shirt",
    "Leather jackets",
  ],
  hu: [
    "Pulóver",
    "Ruha",
    "Kapucnis póló",
    "Póló",
    "Lapos talpú papucs",
    "Rövidnadrág",
    "Szoknya",
    "Farmer",
    "Cipő",
    "Kabát",
    "Magas sarkú cipő",
    "Öltöny",
    "Sapka",
    "Zokni",
    "Ing",
    "Melltartó",
    "Sál",
    "Fürdőruha",
    "Kalap",
    "Kesztyű",
    "Dzseki",
    "Hosszú kabát",
    "Csizma",
    "Napszemüveg",
    "Nyakkendő",
    "Poló",
    "Bőrdzseki",
  ]
};
